trigger:
  branches:
    include:
    - 'master'
    - 'main'

pool:
  vmImage: windows-latest

variables:
- name: buildConfiguration
  value: 'Release'
- name: Version
  value: 1.0.$(Build.BuildId)
- name: buildArgs
  value: '--configuration $(buildConfiguration) -p:Version=$(Version) -p:PackageVersion=$(Version)'
    
steps:
  - task: DotNetCoreCLI@2
    displayName: 'Restore'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'select'
      vstsFeed: 'aeaa4311-673f-4791-a14d-d19ad82f0603'
      arguments: '$(buildArgs)'
  
  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '$(buildArgs)'
  
  - task: DotNetCoreCLI@2
    displayName: 'Test'
    inputs:
      command: 'test'
      projects: '**/*.csproj'
      arguments: '$(buildArgs)'
  
  - task: DotNetCoreCLI@2
    displayName: 'Pack'
    inputs:
      command: 'pack'
      packagesToPack: '**/Ledgerscope.GeographicLocations.csproj'
      versioningScheme: 'byEnvVar'
      versionEnvVar: 'Version'

  - task: PublishPipelineArtifact@1
    displayName: Publish 'drop' artifacts
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifactName: drop
  
  - task: DotNetCoreCLI@2
    displayName: 'Push'
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: 'aeaa4311-673f-4791-a14d-d19ad82f0603'