using Microsoft.CodeAnalysis;
using System;
using System.Text;

namespace Ledgerscope.GeographicLocations.Generator
{
	[Generator]
	public class SysCountryGenerator : IIncrementalGenerator
	{
		public void Initialize(IncrementalGeneratorInitializationContext context)
		{
			context.RegisterPostInitializationOutput((i) =>
			{
				registerWinCountries(i);
			});
		}

		private void registerWinCountries(IncrementalGeneratorPostInitializationContext i)
		{
			string classDefn = @"using System;
using System.Collections.Generic;

namespace Ledgerscope.GeographicLocations
{
	/// <summary>
	/// Representation of a country that Windows knows about.
	/// </summary>
	public partial class SysCountry
	{

<placeholder>

	}
}";
			string buildDateTime = DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss");
			var s = new StringBuilder();
			try
			{
				var countries = SysCountryHelper.GetAllCountries();

				s.AppendLine("		/// <summary>");
				s.AppendLine("		/// Snapshot generated by Ledgerscope.GeographicLocations.Generator with ");
				s.AppendLine("		/// all the countries that Windows on the package-builder machine knows about.");
				s.AppendLine("		/// </summary>");
				s.AppendLine("		/// <remarks>");
				s.AppendLine("		/// Snapshot built " + buildDateTime);
				s.AppendLine("		/// </remarks>");
				s.AppendLine("		public static IEnumerable<SysCountry> GetAll()");
				s.AppendLine("		{");
				
				foreach(var country in countries)
				{
					s.AppendLine($"			{getYielder(country)}");
				}

				s.AppendLine("		}");
			}
			catch (Exception e)
			{
				s.AppendLine("/*");
				s.AppendLine(buildDateTime);
				s.AppendLine(e.Message);
				s.AppendLine(e.StackTrace);
				s.AppendLine("*/");
			}

			classDefn = classDefn.Replace("<placeholder>", s.ToString());

			i.AddSource("SysCountry.g.cs", classDefn);
		}

		private static string getYielder(SysCountry country)
		=> $"yield return new SysCountry(\"{country.Name}\", \"{country.TwoLetterCode}\", \"{country.ThreeLetterCode}\", \"{country.CurrencyCode}\", \"{country.CurrencySymbol}\");";
	}
}
