using Microsoft.CodeAnalysis;
using System;
using System.Text;

namespace Ledgerscope.GeographicLocations.Generator
{
	[Generator]
	public class WindowsCountryGenerator : ISourceGenerator
	{
		public void Execute(GeneratorExecutionContext context)
		{

		}

		public void Initialize(GeneratorInitializationContext context)
		{
			context.RegisterForPostInitialization((i) =>
			{
				registerWinCountries(i);
			});
		}

		private void registerWinCountries(GeneratorPostInitializationContext i)
		{
			string classDefn = @"using System;
using System.Collections.Generic;

namespace Ledgerscope.GeographicLocations
{
	/// <summary>
	/// Representation of a country that Windows knows about.
	/// </summary>
	public partial class WindowsCountry
	{

<placeholder>

	}
}";
			string buildDateTime = DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss");
			var s = new StringBuilder();
			try
			{
				string constructions = WindowsCountryHelper.GetCountryListConstruction();

				s.AppendLine("		/// <summary>");
				s.AppendLine("		/// Snapshot generated by Ledgerscope.GeographicLocations.Generator with ");
				s.AppendLine("		/// all the countries that Windows on the package-builder machine knows about.");
				s.AppendLine("		/// </summary>");
				s.AppendLine("		/// <remarks>");
				s.AppendLine("		/// Snapshot built " + buildDateTime);
				s.AppendLine("		/// </remarks>");
				s.AppendLine("		public static IEnumerable<WindowsCountry> GetAll()");
				s.AppendLine("		{");
				s.AppendLine(constructions);
				s.AppendLine("		}");
			}
			catch (Exception e)
			{
				s.AppendLine("/*");
				s.AppendLine(buildDateTime);
				s.AppendLine(e.Message);
				s.AppendLine(e.StackTrace);
				s.AppendLine("*/");
			}

			classDefn = classDefn.Replace("<placeholder>", s.ToString());

			i.AddSource("WindowsCountry.g.cs", classDefn);
		}
	}
}
